### ISSUE TITLE
Tests pass locally, but fail on CI

### ISSUE THREAD

**Issue by aloussase** [aloussase/gaya#1]
Investigate why this is happening.

**Comment by Xav83** [comment]
Hi @aloussase :slightly_smiling_face: 

I have experimented with your project today, in order to investigate the source of this issue.
After adding a lot of `std::cout` all over the place and running the tests on GitHub Actions, I have found that the segmentation fault come from the creation of a new `env` variable in [types.cpp (line 85](https://github.com/aloussase/gaya/blob/master/lib/types.cpp#L85).

In the [draft I have created](https://github.com/aloussase/gaya/pull/3), I have split the creation of this `env` instance from the call to the `begin_scope` function, to make it more obvious when debugging.

So I have continued to investigate, and look at the `env` constructor, and I can't log anything in the constructor body, which seems to mean that the segmentation fault comes from the construction of an attribute of the `env` class. And it seems to be the fault of the `bindings` attribute, as the creation of a `parent_ptr = std::shared_ptr<env>` isn't probably the issue.

Following that results, I have activated the logs in `robin_hood` library, but without success so far.
So I went of the GitHub repository of the library, and 2 issues could match the one experimented here:
- [Memory blow up for certain payloads when using robin hood unordered node map](https://github.com/martinus/robin-hood-hashing/issues/147)
- [crash because alignment of key is not respected](https://github.com/martinus/robin-hood-hashing/issues/173)

I don't really know what to do next, to help you on that issue.
I hope this will help you to find a fix, and have a successful GitHub Action process :wink: 

PS: Feel free to close the draft I have created if you don't need it. I will let it available so that you can reuse it to continue investigate this issue :wink:

**Comment by aloussase** [comment]
@Xav83 awesome thanks for your help! Will try to investigate further with your insights.
